/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hcmut.cn.appchat.cn_assignment1_applicationchat;


import java.util.List;
import com.hcmut.cn.appchat.cn_assignment1_applicationchat.ServerSocketThread;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.hcmut.cn.appchat.cn_assignment1_applicationchat.ClientInfo;
import com.hcmut.cn.appchat.cn_assignment1_applicationchat.ChatWindow;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
/**
 *
 * @author nguye
 */
public class ListClientUI extends javax.swing.JFrame {
    private static List<ClientInfo> listClient;
    private Socket socket;
    private ChatClient chatClient;
    private ServerSocket serverSocket;
    private List<ClientInfo> connectedList;
    private ServerSocketThread serverSocketThread;
    
    /**
     * Creates new form ListClientUI
     */
    public ListClientUI(List<ClientInfo> listClient) {
        initComponents();
        this.setVisible(true);
        this.listClient = listClient;
    }

    public ListClientUI(ChatClient chatClient, List<ClientInfo> list) {
        this(list);
        this.chatClient = chatClient;
        this.connectedList = new ArrayList<ClientInfo>();
        
        DefaultListModel model = new DefaultListModel();
        
        for (int i = 0; i < list.size(); i++) {
            model.addElement(list.get(i).getDisplayedName());
        }
        
        this.activeUserList.setModel(model);
         
        //ServerSocket serverSocket;
        try {
            serverSocket = new ServerSocket(chatClient.getMyPort());
            serverSocketThread = new ServerSocketThread(serverSocket);
            serverSocketThread.setConnectedList(connectedList);
            serverSocketThread.start();
            
        } catch (IOException ex) {
            Logger.getLogger(ListClientUI.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error when creating ServerSocket");
            ex.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        activeUserList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        activeUserList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        activeUserList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        activeUserList.setVisibleRowCount(-1);
        activeUserList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                activeUserListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(activeUserList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void activeUserListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activeUserListMouseClicked
        // TODO add your handling code here:
        
        if (activeUserList.getSelectedIndex() != -1) {
            System.out.println("Click: " + activeUserList.getSelectedIndex());
            ClientInfo otherInfo = listClient.get(activeUserList.getSelectedIndex());
            
            //this.connectedList = serverSocketThread.getConnectedList();
            List<ClientInfo> list = new ArrayList<>(serverSocketThread.getConnectedList());
            System.out.println("---------------126---");
            System.out.println(this.connectedList.addAll(list));
                        
            if (this.isContainInList(otherInfo)) {                
                return;
            }
            
            connectedList.add(otherInfo);
            serverSocketThread.setConnectedList(connectedList);
            connectedList.clear();
            
            try {
                Socket socketToOther = new Socket(otherInfo.getHost(), otherInfo.getPort());

                ChatWindowThread chatWindowThread = new ChatWindowThread(
                        this.serverSocket,
                        socketToOther,
                        otherInfo
                );
                System.out.println("Socket send");
                chatWindowThread.start();

            } catch (IOException ex) {
                Logger.getLogger(ListClientUI.class.getName()).log(Level.SEVERE, null, ex);
                ex.printStackTrace();
            }
            
        }
        
        activeUserList.clearSelection();
    }//GEN-LAST:event_activeUserListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListClientUI(listClient).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> activeUserList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void listen(int port) {
        ServerSocketThread serverSocketThread;
        ServerSocket serverSocket;
        
        try {
            serverSocket = new ServerSocket(port);
            serverSocketThread = new ServerSocketThread(serverSocket);
            serverSocketThread.start();

            Socket socketReturn;
            while (true) {
                if (serverSocketThread.getSocket() != null) {
                    socketReturn = serverSocketThread.getSocket();
                    serverSocketThread.setNULL();
                    ClientInfo otherClient = new ClientInfo(socketReturn.getInetAddress().getHostAddress(), socketReturn.getPort());
                    
                    
                }
            }
            
            
            

        } catch (IOException ex) {
            Logger.getLogger(ListClientUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    private boolean isContainInList(ClientInfo otherInfo) {
        boolean isContain = false;
        for (int i = 0; i < connectedList.size(); i++) {
            if (connectedList.get(i).getHost().equals(otherInfo.getHost())
                    && connectedList.get(i).getPort() == otherInfo.getPort()) {

                System.out.println("Receive request from: " + otherInfo.getPort());
                isContain = true;

//                        ChatWindow correspondingChatWindow = this.getChatClient(i);
//                        if (correspondingChatWindow != null) {
//                            ReceiveThread receiveThread = new ReceiveThread(returnSocket, correspondingChatWindow);
//                            receiveThread.start();
//                        }
                break;
            }
            System.out.println(connectedList.get(i).getHost() + "|241|" + connectedList.get(i).getPort());
        }
        
        // print array
        for (int i=0; i<connectedList.size(); i++) {
            System.out.println(connectedList.get(i).getPort());
        }
        System.out.println("other port: " + otherInfo.getPort());

        return isContain;
    }
}
